KvartsShop/KvartsShop/Models/SubCatalog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KvartsShop.Models
{
    public class SubCatalog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImagePath { get; set; }
        public int CatalogId { get; set; }
    }
}

KvartsShop/KvartsShop/Areas/Admin/Controllers/SubCatalogController.cs
using KvartsShop.Areas.Admin.Models;
using KvartsShop.Models;
using KvartsShop.Models.Context;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KvartsShop.Areas.Admin.Controllers
{
    public class SubCatalogController : Controller
    {
        DataContext db = new DataContext();
        public ActionResult Del(int id)
        {
            if (Session["userId"] != null)
            {
                if (db.Users.Find(Session["userId"]).Status == Status.admin)
                {
                    db.SubCatalogs.Remove(db.SubCatalogs.Find(id));

                    IEnumerable<SubSubCatalog> subsubcatalogs = db.SubSubCatalogs.Where(subsubcatalog => subsubcatalog.SubCatalogId == id);

                    if (subsubcatalogs != null)
                    {
                        foreach (var subsubcatalog in subsubcatalogs)
                        {
                            db.SubSubCatalogs.Remove(subsubcatalog);
                        }
                    }
                    db.SaveChanges();

                    ViewBag.Products = db.Products;
                    ViewBag.Catalogs = db.Catalogs;
                    ViewBag.SubCatalogs = db.SubCatalogs;
                    ViewBag.SubSubCatalogs = db.SubSubCatalogs;
                    return View("~/Areas/Admin/Views/Home/Admin.cshtml");
                }
                return HttpNotFound();
            }
            return HttpNotFound();
        }

        public ActionResult Create()
        {
            ViewBag.Catalogs = db.Catalogs;
            return View();
        }

        [HttpPost]
        public ActionResult Create(SubCatalogAdmin subcatalogAdmin)
        {
            if (Session["userId"] != null)
            {
                try
                {
                    if (db.Users.Find(Session["userId"]).Status == Status.admin)
                    {
                        SubCatalog subcatalog = new SubCatalog();
                        string sliceOfPath = "/Content/Images/ImageCategory/";
                        if (subcatalogAdmin.File.ContentLength > 0)
                        {
                            string filename = Path.GetFileName(subcatalogAdmin.File.FileName);
                            string filepath = Path.Combine(Server.MapPath("~/Content/Images/ImageCategory"), filename);
                            subcatalogAdmin.File.SaveAs(filepath);
                        }
                        subcatalog.Name = subcatalogAdmin.Name;
                        subcatalog.ImagePath = sliceOfPath + subcatalogAdmin.File.FileName;
                        subcatalog.CatalogId = subcatalogAdmin.CatalogId;

                        db.SubCatalogs.Add(subcatalog);
                        db.SaveChanges();

                        ViewBag.Products = db.Products;
                        ViewBag.Catalogs = db.Catalogs;
                        ViewBag.SubCatalogs = db.SubCatalogs;
                        ViewBag.SubSubCatalogs = db.SubSubCatalogs;
                        return View("~/Areas/Admin/Views/Home/Admin.cshtml");
                    }
                    return HttpNotFound();
                }
                catch (Exception)
                {
                    ViewBag.Products = db.Products;
                    ViewBag.Catalogs = db.Catalogs;
                    ViewBag.SubCatalogs = db.SubCatalogs;
                    ViewBag.SubSubCatalogs = db.SubSubCatalogs;
                    return View("~/Areas/Admin/Views/Home/Admin.cshtml");
                }
            }
            return HttpNotFound();
        }
    }
}

KvartsShop/KvartsShop/Areas/Admin/Views/SubCatalog/Create.cshtml
@model KvartsShop.Models.SubCatalog

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "SubCatalog", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>SubCatalog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="file" class="control-label col-md-2" style="margin-right:10px;">Image</label>
            <input type="file" class="form-control-file" name="File" id="File" style="margin-left:10px;">
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CatalogId, htmlAttributes: new { @class = "control-label col-md-2" })
            <select name="CatalogId" class="form-control">
                @foreach (var catalog in ViewBag.Catalogs)
                {
                    <option value="@catalog.Id">@catalog.Name</option>
                }
            </select>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>