KvartsShop/KvartsShop/Models/Catalog.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KvartsShop.Models
{
    public class Catalog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImagePath { get; set; }
    }
}

KvartsShop/KvartsShop/Areas/Admin/Controllers/CatalogController.cs
using KvartsShop.Areas.Admin.Models;
using KvartsShop.Models;
using KvartsShop.Models.Context;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KvartsShop.Areas.Admin.Controllers
{
    public class CatalogController : Controller
    {
        DataContext db = new DataContext();
        public ActionResult Del(int id)
        {
            if (Session["userId"] != null)
            {
                if (db.Users.Find(Session["userId"]).Status == Status.admin)
                {
                    db.Catalogs.Remove(db.Catalogs.Find(id));

                    IEnumerable<SubCatalog> subcatalogs = db.SubCatalogs.Where(subcatalog => subcatalog.CatalogId == id);
                    IEnumerable<SubSubCatalog> subsubcatalogs = db.SubSubCatalogs.Where(subsubcatalog => subsubcatalog.CatalogId == id);

                    if(subcatalogs != null)
                    {
                        foreach (var subcatalog in subcatalogs)
                        {
                            db.SubCatalogs.Remove(subcatalog);
                        }
                    }

                    if (subsubcatalogs != null)
                    {
                        foreach (var subsubcatalog in subsubcatalogs)
                        {
                            db.SubSubCatalogs.Remove(subsubcatalog);
                        }
                    }
                    db.SaveChanges();

                    ViewBag.Products = db.Products;
                    ViewBag.Catalogs = db.Catalogs;
                    ViewBag.SubCatalogs = db.SubCatalogs;
                    ViewBag.SubSubCatalogs = db.SubSubCatalogs;
                    return View("~/Areas/Admin/Views/Home/Admin.cshtml");
                }
                return HttpNotFound();
            }
            return HttpNotFound();
        }

        public ActionResult Create()
        {
            if (Session["userId"] != null && db.Users.Find(Session["userId"]).Status == Status.admin)
            {
                return View();
            }
            return HttpNotFound();
        }
        [HttpPost]
        public ActionResult Create(CatalogAdmin catalogAdmin)
        {
            if (Session["userId"] != null)
            {
                try
                {
                    if (db.Users.Find(Session["userId"]).Status == Status.admin)
                    {
                        Catalog catalog = new Catalog();
                        string sliceOfPath = "/Content/Images/ImageCategory/";
                        if (catalogAdmin.File.ContentLength > 0)
                        {
                            string filename = Path.GetFileName(catalogAdmin.File.FileName);
                            string filepath = Path.Combine(Server.MapPath("~/Content/Images/ImageCategory"), filename);
                            catalogAdmin.File.SaveAs(filepath);
                        }
                        catalog.Name = catalogAdmin.Name;
                        catalog.ImagePath = sliceOfPath + catalogAdmin.File.FileName;

                        db.Catalogs.Add(catalog);
                        db.SaveChanges();

                        ViewBag.Products = db.Products;
                        ViewBag.Catalogs = db.Catalogs;
                        ViewBag.SubCatalogs = db.SubCatalogs;
                        ViewBag.SubSubCatalogs = db.SubSubCatalogs;
                        return View("~/Areas/Admin/Views/Home/Admin.cshtml");
                    }
                    return HttpNotFound();
                }
                catch (Exception e)
                {
                    ViewBag.Products = db.Products;
                    ViewBag.Catalogs = db.Catalogs;
                    ViewBag.SubCatalogs = db.SubCatalogs;
                    ViewBag.SubSubCatalogs = db.SubSubCatalogs;
                    return View("~/Areas/Admin/Views/Home/Admin.cshtml");
                }
            }
            return HttpNotFound();           
        }
    }
}

KvartsShop/KvartsShop/Areas/Admin/Views/Catalog/Create.cshtml
@model KvartsShop.Models.Catalog

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Catalog", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Catalog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label for="file" class="control-label col-md-2" style="margin-right:10px;">Image</label>
            <input type="file" class="form-control-file" name="File" id="File" style="margin-left:10px;">
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>